# Generated by Django 5.1.4 on 2025-01-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institution',
        ),
    ]
