# Generated by Django 5.1.4 on 2025-01-11 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_avaialble_institutions_and_more'),
        ('users', '0003_remove_customuser_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_institution', models.BooleanField(default=False)),
                ('is_learner', models.BooleanField(default=False)),
                ('available_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.availableinstitution')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
