# Generated by Django 5.1.4 on 2025-01-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_updatecustomuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatecustomuser',
            old_name='available_institution',
            new_name='available_institution_user',
        ),
        migrations.RemoveField(
            model_name='updatecustomuser',
            name='is_institution',
        ),
        migrations.RemoveField(
            model_name='updatecustomuser',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='updatecustomuser',
            name='is_learner',
        ),
    ]
