# Generated by Django 5.1.4 on 2025-01-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_avaialble_institutions_and_more'),
        ('users', '0008_alter_updatecustomuser_available_institution_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecustomuser',
            name='available_institution_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.availableinstitution'),
        ),
    ]
