# Generated by Django 5.1.4 on 2025-01-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_updatecustomuser_available_institution_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateCustomUser',
        ),
    ]
