# Generated by Django 5.1.4 on 2025-01-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_avaialble_institutions_and_more'),
        ('users', '0010_delete_updatecustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='available_institutions',
            field=models.ManyToManyField(related_name='available_users', to='institutions.availableinstitution'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution_works_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
    ]
