# Generated by Django 5.1.4 on 2025-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_avaialble_institutions_and_more'),
        ('users', '0011_customuser_available_institutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_institutions',
            field=models.ManyToManyField(related_name='institutions', to='institutions.availableinstitution'),
        ),
    ]
