# Generated by Django 5.1.4 on 2025-01-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_avaialble_institutions_and_more'),
        ('users', '0012_alter_customuser_available_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institution_works_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_working_for_institution', to='institutions.institution'),
        ),
    ]
