# Generated by Django 5.1.4 on 2025-01-11 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_alter_institution_users'),
        ('users', '0013_alter_customuser_institution_works_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='available_institutions',
            field=models.ManyToManyField(blank=True, to='institutions.availableinstitution'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution_works_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution'),
        ),
    ]
