volumes:
  db-data:
  web-media:
  log-data:


networks:
  network:
    driver: bridge

services:
  db:
    image: postgres:latest
    networks:
      - network
    container_name: courses_db
    restart: always
    environment:
      - POSTGRES_DB=courses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Fixed port mapping

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbit
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5682:5672"
      - "15682:15672"
    networks:
      - network

  web:
    # <-- Ensure this is at the same indentation level as `db` and `rabbitmq`
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8082:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=courses
      - DB_USER=postgres
      - DB_PASSWORD=@emin12332#@#!#@poeres

  pgadmin:
    # Added pgAdmin service
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - network
    depends_on:
      - db
