# Generated by Django 5.1.4 on 2025-01-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quizzes',
        ),
    ]
