# Generated by Django 5.1.4 on 2025-01-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_unique_together'),
        ('institutions', '0003_remove_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institution'),
        ),
    ]
