# Generated by Django 5.1.4 on 2025-01-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
    ]
