# Generated by Django 5.1.4 on 2025-01-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('select', 'Select a category'), ('it', 'IT'), ('business', 'Business'), ('language', 'Language'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('science', 'Science'), ('politics', 'Politics'), ('art', 'Art'), ('sports', 'Sports'), ('history', 'History'), ('travel', 'Travel'), ('other', 'Other')], default='select', max_length=10, null=True),
        ),
    ]
