# Generated by Django 4.2.18 on 2025-01-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
