# Generated by Django 5.1.4 on 2025-01-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='course',
        ),
    ]
