# Generated by Django 5.1.4 on 2025-01-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_institution'),
        ('forums', '0002_remove_thread_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='courses.course'),
        ),
    ]
