# Generated by Django 5.1.4 on 2025-01-12 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_webinarattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='participants',
        ),
        migrations.AddField(
            model_name='webinarattendance',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='webinars_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
