# Generated by Django 5.1.4 on 2025-01-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_remove_webinar_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarattendance',
            name='participants',
        ),
    ]
