# Generated by Django 5.1.4 on 2025-01-08 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='users',
            field=models.ManyToManyField(related_name='institutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
