# Generated by Django 5.1.4 on 2025-01-11 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_remove_institution_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='avaialble_institutions',
            field=models.ManyToManyField(related_name='institutions_available', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
