# Generated by Django 5.1.4 on 2025-01-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_institution_avaialble_institutions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='avaialble_institutions',
        ),
        migrations.CreateModel(
            name='AvailableInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
        ),
    ]
