# Generated by Django 5.1.4 on 2025-01-11 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_institution_avaialble_institutions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='users',
            field=models.ManyToManyField(related_name='institution_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
