# Generated by Django 5.1.4 on 2025-01-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_alter_institution_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableinstitution',
            name='available_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_institutions', to='institutions.institution'),
        ),
    ]
